version: '3.8'

services:
  market-analysis-api:
    build: .
    container_name: market-analysis-agent
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      - GROQ_API_KEY=${GROQ_API_KEY:-}
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - market-analysis-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for caching (for production)
  redis:
    image: redis:7-alpine
    container_name: market-analysis-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - market-analysis-network
    restart: unless-stopped
    command: redis-server --appendonly yes

networks:
  market-analysis-network:
    driver: bridge

volumes:
  redis-data: